#!/usr/bin/env bash
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/analytics -d analytics.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/AsyncStageout -d AsyncStageout.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/cmssh -d cmssh.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/ContinuousIntegration -d ContinuousIntegration.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/CRAB2 -d CRAB2.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/CRABClient -d CRABClient.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/CRABServer -d CRABServer.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DAS -d das.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DASMaps -d DASMaps.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DBS -d DBS.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DBSAPI -d DBSAPI.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DDM -d DDM.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/deployment -d deployment.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DLSAPI -d DLSAPI.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DMWMAnalytics -d DMWMAnalytics.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DMWMMON -d DMWMMON.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/DQIS -d DQIS.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/FileMover -d FileMover.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/LifeCycle -d LifeCycle.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/overview -d overview.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/PHEDEX -d PHEDEX.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/ProdCommon -d ProdCommon.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/Sandbox -d Sandbox.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/sitedb -d sitedb.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/StageManager -d StageManager.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/T0 -d T0.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/t0wmadatasvc -d t0wmadatasvc.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/tutorials -d tutorials.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/WMArchive -d WMArchive.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/WMCore -d WMCore.deps
./projectLibAnalyzer.sh -p /home/adelina/cern/all_dmwm/WMCore-legacy -d WMCore-legacy.deps
